# Generated by Django 6.1.1 on 2026-09-02 18:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=255)),
                ('app_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('icon_reference', models.CharField(blank=True, default='', max_length=255)),
                ('is_system_app', models.BooleanField(default=False)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_apps', to='devices.device')),
            ],
            options={
                'ordering': ['app_name'],
                'unique_together': {('device', 'package_name')},
            },
        ),
        migrations.CreateModel(
            name='UsageSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('system', 'System Usage Stats'), ('manual', 'Manual Entry'), ('import', 'Data Import')], default='system', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_sessions', to='devices.device')),
                ('installed_app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='usage.installedapp')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['device', 'start_time'], name='usage_usage_device__aabbd1_idx'), models.Index(fields=['installed_app', 'start_time'], name='usage_usage_install_e1066b_idx'), models.Index(fields=['package_name', 'start_time'], name='usage_usage_package_0e0577_idx')],
            },
        ),
    ]
